import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: "400", style: "normal" });

export const metadata: Metadata = {
  title: "A M A N T I X",
  description: "Generated by create next app",
  icons: {
    icon: "/svgs/logotab.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/svgs/logotab.svg" type="image/svg+xml" />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
